### ISSUE TITLE
auto-fill maximum dollar-signs in modal, users can trim it down if they want.

### ISSUE THREAD

**Issue by desmondmullen** [jskwru11/project-1#45]

**Comment by desmondmullen** [comment]
To find every restaurant would a user click all the dollar sign choices? Or is the dollar sign thing a maximum like if I select $$$ I will get that and anything less expensive than that.

**Comment by danieldayton33** [comment]
I fixed it. I just added an if statement that sets the array to all four ranges if none are selected. It works by filtering only for the clicked value. So now we have all values unless someone selects one or more of the price ranges. this is how yelp does it too.
